proxy_http_version 1.1;
#backend is the conatiner name(here we actuullay use ip or dns, hwovwer in docker we use docker container name as dns)
location /api/ { proxy_pass http://localhost:8080/; }

location /health {
  stub_status on;
  access_log off;
}