# version: "3"
# networks:
#   expense:
# volumes:
#   mysql:
# services:
#   mysql:
#     image: kdprasad028/mysql_july:v1
#     container_name: mysql
#     volumes:
#     - mysql:/var/lib/mysql
  
#   backend:
#     image: kdprasad028/backend_july:v1
#     container_name: backend
#     command: sh -c "sleep 10 && node /opt/server/index.js"
#     depends_on:
#       - mysql
    
#   frontend:
#     image: kdprasad028/frontend_july:v1
#     container_name: frontend
#     depends_on:
#       - backend
#     ports:
#       - 80:80 

version: "3"

networks:
  expense:

volumes:
  mysql:

services:
  mysql:
    image: kdprasad028/mysql_july:v1
    container_name: mysql
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - expense

  backend:
    image: kdprasad028/backend_july:v1
    container_name: backend
    command: sh -c "sleep 10 && node /opt/server/index.js"
    depends_on:
      - mysql
    networks:
      - expense

  frontend:
    image: kdprasad028/frontend_july:v1
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - expense